namespace MTArt.Catalog.Application.Products.Dtos;

/// <summary>Card-sized projection for /products listing pages - never carries full description/HTML.</summary>
public sealed record ProductListItemDto(
    Guid Id,
    string Reference,
    string Slug,
    string Name,
    string? ShortDescription,
    Guid CategoryId,
    string CategorySlug,
    string CategoryName,
    Guid? CollectionId,
    string? CollectionSlug,
    Guid? PrimaryImageId,
    Guid? HoverImageId,
    string? PrimaryImageUrl,
    string? HoverImageUrl,
    bool IsFeatured,
    bool IsNew,
    bool IsCustomizable,
    bool IsSimulatorReady,
    bool IsInStock,
    string Status,
    string CatalogKind,
    decimal? PricePerM2,
    string Currency,
    string PriceVisibility,
    string? PatternSlug,
    IReadOnlyList<string> RepresentativeColorNames,
    IReadOnlyList<string> RepresentativeFormatLabels);

public sealed record ProductVariantDto(
    Guid Id,
    string Sku,
    string Reference,
    Guid ColorId,
    string ColorCode,
    string ColorName,
    string? ColorHexApproximation,
    Guid FormatId,
    string FormatLabel,
    Guid? FinishId,
    string? FinishName,
    string StockStatus,
    decimal UnitsPerM2,
    decimal WeightPerM2Kg,
    decimal ThicknessCm,
    decimal? MinimumOrder);

public sealed record ProductImageDto(Guid Id, Guid MediaId, string? ImageUrl, string Role, int DisplayOrder);

public sealed record RelatedProductDto(Guid Id, string Slug, string Name, Guid? PrimaryImageId);

public sealed record ProductDetailDto(
    Guid Id,
    string Reference,
    string Slug,
    string Name,
    string? ShortDescription,
    string? Description,
    string? Craftsmanship,
    string? InstallationAdvice,
    string? MaintenanceAdvice,
    Guid CategoryId,
    string CategorySlug,
    string CategoryName,
    Guid? CollectionId,
    string? CollectionSlug,
    string? CollectionName,
    Guid? ShapeId,
    string? ShapeName,
    Guid? FinishId,
    string? FinishName,
    bool IsFeatured,
    bool IsNew,
    bool IsCustomizable,
    bool IsInStock,
    decimal? MinimumOrderM2,
    decimal? UnitsPerSquareMeter,
    decimal? WeightPerSquareMeterKg,
    decimal? ThicknessCm,
    string? CountryOfOrigin,
    string? Material,
    string? ProductionLeadTime,
    decimal? PricePerM2,
    string Currency,
    string PriceVisibility,
    bool IsSimulatorReady,
    string CatalogKind,
    Guid? PatternId,
    string? PatternSlug,
    string Status,
    string? SeoTitle,
    string? SeoDescription,
    IReadOnlyList<ProductImageDto> Images,
    IReadOnlyList<ProductVariantDto> Variants,
    IReadOnlyList<RelatedProductDto> RelatedProducts);

public sealed record ProductTranslationDto(
    string LanguageCode,
    string Name,
    string? ShortDescription,
    string? Description,
    string? Craftsmanship,
    string? InstallationAdvice,
    string? MaintenanceAdvice,
    string? SeoTitle,
    string? SeoDescription);
