<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MTArt.Catalog.Application\MTArt.Catalog.Application.csproj" />
    <ProjectReference Include="..\MTArt.Catalog.Infrastructure\MTArt.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\MTArt.Observability\MTArt.Observability.csproj" />
  </ItemGroup>

</Project>
