// <auto-generated />
using System;
using MTArt.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTArt.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTArt.Catalog.Domain.Categories.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Categories", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Categories.ProductCategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("CategoryTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Collections.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Collections", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Collections.CollectionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Story")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("CollectionTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Colors.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("HexApproximation")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("TextureImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rgb")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TextureImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDemo");

                    b.HasIndex("MaterialType");

                    b.HasIndex("Source");

                    b.ToTable("Colors", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Colors.ColorTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ColorTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Finishes.Finish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Finishes", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Finishes.FinishTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FinishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FinishId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("FinishTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Formats.Format", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DiagramImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("HasVerifiedTechnicalData")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ShapeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ThicknessCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("UnitsPerM2")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("WeightPerM2Kg")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("WeightPerUnitKg")
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal>("WidthCm")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialType");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("ShapeId");

                    b.ToTable("Formats", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Formats.FormatTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FormatId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("FormatTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Imports.CatalogImportPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DetectedShape")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DominantColors")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("ExtractedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<double>("ImportConfidence")
                        .HasColumnType("float");

                    b.Property<string>("ImportId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("ImportedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("bit");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("PriceUnit")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SuggestedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SuggestedReference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("SessionId");

                    b.ToTable("CatalogImportPages", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Imports.CatalogImportSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("int");

                    b.Property<int>("NeedsReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("ProductsDetected")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsDetected")
                        .HasColumnType("int");

                    b.Property<string>("SourceCatalog")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("UnknownPages")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("CatalogImportSessions", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.PatternCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PatternCategories", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.PatternCategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("PatternCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatternCategoryId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("PatternCategoryTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.TilePattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasePreviewImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BasePreviewImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSimulatorReady")
                        .HasColumnType("bit");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RegionCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("VectorAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VectorAssetUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsSimulatorReady");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("TilePatterns", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.TilePatternRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("PatternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PatternId", "RegionKey")
                        .IsUnique();

                    b.ToTable("TilePatternRegions", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.TilePatternTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid>("PatternId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatternId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("TilePatternTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.CustomDesigns.CustomTileDesign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RepeatMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("SourceMouldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SvgMarkup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailSvg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("WidthCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("CustomTileDesigns", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CatalogKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("FinishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSimulatorReady")
                        .HasColumnType("bit");

                    b.Property<string>("Material")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("MinimumOrderM2")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid?>("PatternId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PricePerM2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PriceVisibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ProductionLeadTime")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ShapeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceCatalog")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("ThicknessCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("UnitsPerSquareMeter")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("WeightPerSquareMeterKg")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogKind");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("IsDemo");

                    b.HasIndex("IsSimulatorReady");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Products", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.ProductRelatedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RelatedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductRelatedProducts", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.ProductTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Craftsmanship")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InstallationAdvice")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaintenanceAdvice")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ProductTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FinishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MinimumOrder")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("ThicknessCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("UnitsPerM2")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("WeightPerM2Kg")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("ProductVariants", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Shapes.Shape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Shapes", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Shapes.ShapeTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ShapeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShapeId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ShapeTranslations", "catalog");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Categories.ProductCategory", b =>
                {
                    b.OwnsOne("MTArt.Catalog.Domain.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ProductCategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("Slug");

                            b1.HasKey("ProductCategoryId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Categories", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductCategoryId");
                        });

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Categories.ProductCategoryTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Categories.ProductCategory", null)
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Collections.Collection", b =>
                {
                    b.OwnsOne("MTArt.Catalog.Domain.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("CollectionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("Slug");

                            b1.HasKey("CollectionId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Collections", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("CollectionId");
                        });

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Collections.CollectionTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Collections.Collection", null)
                        .WithMany("Translations")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Colors.Color", b =>
                {
                    b.OwnsOne("MTArt.Catalog.Domain.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ColorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("Slug");

                            b1.HasKey("ColorId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Colors", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ColorId");
                        });

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Colors.ColorTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Colors.Color", null)
                        .WithMany("Translations")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Finishes.FinishTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Finishes.Finish", null)
                        .WithMany("Translations")
                        .HasForeignKey("FinishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Formats.FormatTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Formats.Format", null)
                        .WithMany("Translations")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Imports.CatalogImportPage", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Imports.CatalogImportSession", null)
                        .WithMany("Pages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.PatternCategory", b =>
                {
                    b.OwnsOne("MTArt.Catalog.Domain.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("PatternCategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("Slug");

                            b1.HasKey("PatternCategoryId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("PatternCategories", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("PatternCategoryId");
                        });

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.PatternCategoryTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Patterns.PatternCategory", null)
                        .WithMany("Translations")
                        .HasForeignKey("PatternCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.TilePattern", b =>
                {
                    b.OwnsOne("MTArt.Catalog.Domain.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("TilePatternId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("Slug");

                            b1.HasKey("TilePatternId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("TilePatterns", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("TilePatternId");
                        });

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.TilePatternRegion", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Patterns.TilePattern", null)
                        .WithMany("Regions")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.TilePatternTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Patterns.TilePattern", null)
                        .WithMany("Translations")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.Product", b =>
                {
                    b.OwnsOne("MTArt.Catalog.Domain.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("nvarchar(160)")
                                .HasColumnName("Slug");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.ProductImage", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Products.Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.ProductRelatedProduct", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Products.Product", null)
                        .WithMany("RelatedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.ProductTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Products.Product", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.ProductVariant", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Products.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Shapes.ShapeTranslation", b =>
                {
                    b.HasOne("MTArt.Catalog.Domain.Shapes.Shape", null)
                        .WithMany("Translations")
                        .HasForeignKey("ShapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Categories.ProductCategory", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Collections.Collection", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Colors.Color", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Finishes.Finish", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Formats.Format", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Imports.CatalogImportSession", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.PatternCategory", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Patterns.TilePattern", b =>
                {
                    b.Navigation("Regions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Products.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RelatedProducts");

                    b.Navigation("Translations");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MTArt.Catalog.Domain.Shapes.Shape", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
